anchor_version = "0.28.0"
solana_version = "1.16.12"

[features]
seeds = false
skip-lint = false

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./tests/test-key.json"

[programs.localnet]
smart_wallet = "3dQhmbCccZTtU1KYqW13XCD5CDKgw4s6NoiGLqPwv4QF"
govern = "HWKB16ucqqFRZ5W768FA58fVuqJLGw6v9YdGtmfBUAgj"
met_voter = "voteXZxajNhmCGpqzBhVArCANMKra5nwqtaaLA6v9CX"
locked_voter = "GJ3DSRYMLRoqjVgtj1JwdFXQU4FNzvgjGUfYyE4u1JMa"
merkle_distributor = "MRKgRBL5XCCT5rwUGnim4yioq9wR4c6rj2EZkw8KdyZ"